---
- name: Remove Storage account
  azure.azcollection.azure_rm_storageaccount:
    name: "{{ item }}"
    state: absent
    resource_group: "{{ resource_group_name }}"
    force_delete_nonempty: yes
  loop: "{{ storage_account_names }}"
